include /etc/nginx/hydra-upstream.conf;
server {
  listen 8080;
  client_max_body_size 2m;
  location ~ ^/(oauth2/|\.well-known/|userinfo$) {
    proxy_pass http://hydra_active;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location / {
    proxy_pass http://portal:3000;
    proxy_set_header Host $http_host;
  }
}
